document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
document.getElementById('classimg').src ='https://raw.githubusercontent.com/Wither19/thatdivisaspy/main/docs/assets/images/Scout_RED.png'; document.getElementById('meettheclass').innerHTML = 'Meet The Scout'; document.getElementById('classname').innerHTML = 'Real name: Jeremy'; document.getElementById('classage').innerHTML = 'Age: 27';
document.getElementById('classresidence').innerHTML = 'Boston, MA';
document.getElementById('primary').innerHTML = 'Scattergun';
document.getElementById('secondary').innerHTML = 'Pistol';
document.getElementById('melee').innerHTML = 'Bat';
document.getElementById('pda1').style.display = 'none';
document.getElementById('pda2').style.display = 'none';
